#!/usr/bin/python3
"""Python script to gegerate Authors of the Airbnb clone repository"""

from git import Repo
import os

# Get the current directory
current_dir = os.getcwd()

# Initialize the repository object
repo = Repo(current_dir)

# Output file path for the Authors file
output_file = os.path.join(current_dir, "AUTHORS")

# Get the list of contributors from the commit history
contributors = set()

for commit in repo.iter_commits():
    contributors.add(commit.author)

# Write the contributors' information to the Authors file
with open(output_file, 'w') as f:
    f.write("# File @generated by generate-authors.py script\n")
    f.write("# This file lists all contributors to the repository.\n")
    f.write("# Auto-generated, do not edit manually.\n")
    f.write("\n")

    for contributor in contributors:
        f.write(f"{contributor.name} <{contributor.email}>\n")
